# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calc.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 430)
        MainWindow.setStyleSheet("background-color: rgb(138, 186, 211);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn7 = QtWidgets.QPushButton(self.centralwidget)
        self.btn7.setEnabled(True)
        self.btn7.setGeometry(QtCore.QRect(10, 100, 100, 70))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn7.setFont(font)
        self.btn7.setStyleSheet(" QPushButton {\n"
                                "     border: 2px solid rgb(0, 0, 0);\n"
                                "     border-radius:10;\n"
                                "     color:#F5DFBB;\n"
                                "     background-color: rgb(62, 137, 137);\n"
                                "     \n"
                                "     min-width: 80px;\n"
                                " }\n"
                                "\n"
                                " QPushButton:pressed {\n"
                                "     \n"
                                "    \n"
                                "    background-color: rgb(0, 174, 255);\n"
                                " }\n"
                                "\n"
                                "")
        self.btn7.setObjectName("btn7")
        self.btn_result = QtWidgets.QPushButton(self.centralwidget)
        self.btn_result.setEnabled(True)
        self.btn_result.setGeometry(QtCore.QRect(10, 10, 381, 81))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.btn_result.setFont(font)
        self.btn_result.setStyleSheet(" QPushButton {\n"
                                      "     border: 2px solid #000000;\n"
                                      "     border-radius:;\n"
                                      "     color:#F5DFBB;\n"
                                      "     background-color: rgb(62, 137, 137);\n"
                                      "     \n"
                                      "     min-width: 80px;\n"
                                      " }\n"
                                      "\n"
                                      " QPushButton:pressed {\n"
                                      "     \n"
                                      "    \n"
                                      "    background-color: rgb(0, 174, 255);\n"
                                      " }\n"
                                      "\n"
                                      "")
        self.btn_result.setObjectName("btn_result")
        self.btn8 = QtWidgets.QPushButton(self.centralwidget)
        self.btn8.setEnabled(True)
        self.btn8.setGeometry(QtCore.QRect(120, 100, 100, 70))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn8.setFont(font)
        self.btn8.setStyleSheet(" QPushButton {\n"
                                "     border: 2px solid rgb(0, 0, 0);\n"
                                "     border-radius:10;\n"
                                "     color:#F5DFBB;\n"
                                "     background-color: rgb(62, 137, 137);\n"
                                "     \n"
                                "     min-width: 80px;\n"
                                " }\n"
                                "\n"
                                " QPushButton:pressed {\n"
                                "     \n"
                                "    \n"
                                "    background-color: rgb(0, 174, 255);\n"
                                " }\n"
                                "\n"
                                "")
        self.btn8.setObjectName("btn8")
        self.btn9 = QtWidgets.QPushButton(self.centralwidget)
        self.btn9.setEnabled(True)
        self.btn9.setGeometry(QtCore.QRect(230, 100, 100, 70))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn9.setFont(font)
        self.btn9.setStyleSheet(" QPushButton {\n"
                                "     border: 2px solid rgb(0, 0, 0);\n"
                                "     border-radius:10;\n"
                                "     color:#F5DFBB;\n"
                                "     background-color: rgb(62, 137, 137);\n"
                                "     \n"
                                "     min-width: 80px;\n"
                                " }\n"
                                "\n"
                                " QPushButton:pressed {\n"
                                "     \n"
                                "    \n"
                                "    background-color: rgb(0, 174, 255);\n"
                                " }\n"
                                "\n"
                                "")
        self.btn9.setObjectName("btn9")
        self.btn4 = QtWidgets.QPushButton(self.centralwidget)
        self.btn4.setEnabled(True)
        self.btn4.setGeometry(QtCore.QRect(10, 180, 100, 70))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn4.setFont(font)
        self.btn4.setStyleSheet(" QPushButton {\n"
                                "     border: 2px solid rgb(0, 0, 0);\n"
                                "     border-radius:10;\n"
                                "     color:#F5DFBB;\n"
                                "     background-color: rgb(62, 137, 137);\n"
                                "     \n"
                                "     min-width: 80px;\n"
                                " }\n"
                                "\n"
                                " QPushButton:pressed {\n"
                                "     \n"
                                "    \n"
                                "    background-color: rgb(0, 174, 255);\n"
                                " }\n"
                                "\n"
                                "")
        self.btn4.setObjectName("btn4")
        self.btn5 = QtWidgets.QPushButton(self.centralwidget)
        self.btn5.setEnabled(True)
        self.btn5.setGeometry(QtCore.QRect(120, 180, 100, 70))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn5.setFont(font)
        self.btn5.setStyleSheet(" QPushButton {\n"
                                "     border: 2px solid rgb(0, 0, 0);\n"
                                "     border-radius:10;\n"
                                "     color:#F5DFBB;\n"
                                "     background-color: rgb(62, 137, 137);\n"
                                "     \n"
                                "     min-width: 80px;\n"
                                " }\n"
                                "\n"
                                " QPushButton:pressed {\n"
                                "     \n"
                                "    \n"
                                "    background-color: rgb(0, 174, 255);\n"
                                " }\n"
                                "\n"
                                "")
        self.btn5.setObjectName("btn5")
        self.btn6 = QtWidgets.QPushButton(self.centralwidget)
        self.btn6.setEnabled(True)
        self.btn6.setGeometry(QtCore.QRect(230, 180, 100, 70))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn6.setFont(font)
        self.btn6.setStyleSheet(" QPushButton {\n"
                                "     border: 2px solid rgb(0, 0, 0);\n"
                                "     border-radius:10;\n"
                                "     color:#F5DFBB;\n"
                                "     background-color: rgb(62, 137, 137);\n"
                                "     \n"
                                "     min-width: 80px;\n"
                                " }\n"
                                "\n"
                                " QPushButton:pressed {\n"
                                "     \n"
                                "    \n"
                                "    background-color: rgb(0, 174, 255);\n"
                                " }\n"
                                "\n"
                                "")
        self.btn6.setObjectName("btn6")
        self.btn1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn1.setEnabled(True)
        self.btn1.setGeometry(QtCore.QRect(10, 260, 100, 70))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn1.setFont(font)
        self.btn1.setStyleSheet(" QPushButton {\n"
                                "     border: 2px solid rgb(0, 0, 0);\n"
                                "     border-radius:10;\n"
                                "     color:#F5DFBB;\n"
                                "     background-color: rgb(62, 137, 137);\n"
                                "     \n"
                                "     min-width: 80px;\n"
                                " }\n"
                                "\n"
                                " QPushButton:pressed {\n"
                                "     \n"
                                "    \n"
                                "    background-color: rgb(0, 174, 255);\n"
                                " }\n"
                                "\n"
                                "")
        self.btn1.setObjectName("btn1")
        self.btn2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn2.setEnabled(True)
        self.btn2.setGeometry(QtCore.QRect(120, 260, 100, 70))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn2.setFont(font)
        self.btn2.setStyleSheet(" QPushButton {\n"
                                "     border: 2px solid rgb(0, 0, 0);\n"
                                "     border-radius:10;\n"
                                "     color:#F5DFBB;\n"
                                "     background-color: rgb(62, 137, 137);\n"
                                "     \n"
                                "     min-width: 80px;\n"
                                " }\n"
                                "\n"
                                " QPushButton:pressed {\n"
                                "     \n"
                                "    \n"
                                "    background-color: rgb(0, 174, 255);\n"
                                " }\n"
                                "\n"
                                "")
        self.btn2.setObjectName("btn2")
        self.btn3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn3.setEnabled(True)
        self.btn3.setGeometry(QtCore.QRect(230, 260, 100, 70))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn3.setFont(font)
        self.btn3.setStyleSheet(" QPushButton {\n"
                                "     border: 2px solid rgb(0, 0, 0);\n"
                                "     border-radius:10;\n"
                                "     color:#F5DFBB;\n"
                                "     background-color: rgb(62, 137, 137);\n"
                                "     \n"
                                "     min-width: 80px;\n"
                                " }\n"
                                "\n"
                                " QPushButton:pressed {\n"
                                "     \n"
                                "    \n"
                                "    background-color: rgb(0, 174, 255);\n"
                                " }\n"
                                "\n"
                                "")
        self.btn3.setObjectName("btn3")
        self.btn_plus = QtWidgets.QPushButton(self.centralwidget)
        self.btn_plus.setGeometry(QtCore.QRect(340, 100, 50, 70))
        self.btn_plus.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_plus.setFont(font)
        self.btn_plus.setStyleSheet(" QPushButton {\n"
                                    "     border: 2px solid rgb(0, 0, 0);\n"
                                    "     border-radius:10;\n"
                                    "     color:#F5DFBB;\n"
                                    "     background-color: rgb(62, 137, 137);\n"
                                    "     \n"
                                    "\n"
                                    " }\n"
                                    "\n"
                                    " QPushButton:pressed {\n"
                                    "     \n"
                                    "    \n"
                                    "    background-color: rgb(0, 174, 255);\n"
                                    " }\n"
                                    "")
        self.btn_plus.setObjectName("btn_plus")
        self.btn_minus = QtWidgets.QPushButton(self.centralwidget)
        self.btn_minus.setGeometry(QtCore.QRect(340, 180, 50, 70))
        self.btn_minus.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_minus.setFont(font)
        self.btn_minus.setStyleSheet(" QPushButton {\n"
                                     "     border: 2px solid rgb(0, 0, 0);\n"
                                     "     border-radius:10;\n"
                                     "     color:#F5DFBB;\n"
                                     "     background-color: rgb(62, 137, 137);\n"
                                     "     \n"
                                     "\n"
                                     " }\n"
                                     "\n"
                                     " QPushButton:pressed {\n"
                                     "     \n"
                                     "    \n"
                                     "    background-color: rgb(0, 174, 255);\n"
                                     " }\n"
                                     "")
        self.btn_minus.setObjectName("btn_minus")
        self.buton_mult = QtWidgets.QPushButton(self.centralwidget)
        self.buton_mult.setGeometry(QtCore.QRect(340, 260, 50, 70))
        self.buton_mult.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.buton_mult.setFont(font)
        self.buton_mult.setStyleSheet(" QPushButton {\n"
                                      "     border: 2px solid rgb(0, 0, 0);\n"
                                      "     border-radius:10;\n"
                                      "     color:#F5DFBB;\n"
                                      "     background-color: rgb(62, 137, 137);\n"
                                      "     \n"
                                      "  \n"
                                      " }\n"
                                      "\n"
                                      " QPushButton:pressed {\n"
                                      "     \n"
                                      "    \n"
                                      "    background-color: rgb(0, 174, 255);\n"
                                      " }\n"
                                      "")
        self.buton_mult.setObjectName("buton_mult")
        self.button_division = QtWidgets.QPushButton(self.centralwidget)
        self.button_division.setGeometry(QtCore.QRect(340, 340, 50, 70))
        self.button_division.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.button_division.setFont(font)
        self.button_division.setStyleSheet(" QPushButton {\n"
                                           "     border: 2px solid rgb(0, 0, 0);\n"
                                           "     border-radius:10;\n"
                                           "     color:#F5DFBB;\n"
                                           "     background-color: rgb(62, 137, 137);\n"
                                           "     \n"
                                           "\n"
                                           " }\n"
                                           "\n"
                                           " QPushButton:pressed {\n"
                                           "     \n"
                                           "    \n"
                                           "    background-color: rgb(0, 174, 255);\n"
                                           " }\n"
                                           "")
        self.button_division.setObjectName("button_division")
        self.btn_equal = QtWidgets.QPushButton(self.centralwidget)
        self.btn_equal.setEnabled(True)
        self.btn_equal.setGeometry(QtCore.QRect(120, 340, 211, 70))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_equal.setFont(font)
        self.btn_equal.setStyleSheet(" QPushButton {\n"
                                     "     border: 2px solid rgb(0, 0, 0);\n"
                                     "     border-radius:10;\n"
                                     "     color:#F5DFBB;\n"
                                     "     \n"
                                     "    background-color: rgb(52, 106, 126);\n"
                                     "     \n"
                                     "     min-width: 80px;\n"
                                     " }\n"
                                     "\n"
                                     " QPushButton:pressed {\n"
                                     "     \n"
                                     "    \n"
                                     "    background-color: rgb(0, 174, 255);\n"
                                     " }\n"
                                     "\n"
                                     "")
        self.btn_equal.setObjectName("btn_equal")
        self.btn0 = QtWidgets.QPushButton(self.centralwidget)
        self.btn0.setEnabled(True)
        self.btn0.setGeometry(QtCore.QRect(10, 340, 100, 70))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn0.setFont(font)
        self.btn0.setStyleSheet(" QPushButton {\n"
                                "     border: 2px solid rgb(0, 0, 0);\n"
                                "     border-radius:10;\n"
                                "     color:#F5DFBB;\n"
                                "     background-color: rgb(62, 137, 137);\n"
                                "     \n"
                                "     min-width: 80px;\n"
                                " }\n"
                                "\n"
                                " QPushButton:pressed {\n"
                                "     \n"
                                "    \n"
                                "    background-color: rgb(0, 174, 255);\n"
                                " }\n"
                                "\n"
                                "")
        self.btn0.setObjectName("btn0")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.add_functions()

        self.is_equal = False

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Калькулятор"))
        self.btn7.setText(_translate("MainWindow", "7"))
        self.btn_result.setText(_translate("MainWindow", ""))
        self.btn8.setText(_translate("MainWindow", "8"))
        self.btn9.setText(_translate("MainWindow", "9"))
        self.btn4.setText(_translate("MainWindow", "4"))
        self.btn5.setText(_translate("MainWindow", "5"))
        self.btn6.setText(_translate("MainWindow", "6"))
        self.btn1.setText(_translate("MainWindow", "1"))
        self.btn2.setText(_translate("MainWindow", "2"))
        self.btn3.setText(_translate("MainWindow", "3"))
        self.btn_plus.setText(_translate("MainWindow", "+"))
        self.btn_minus.setText(_translate("MainWindow", "-"))
        self.buton_mult.setText(_translate("MainWindow", "*"))
        self.button_division.setText(_translate("MainWindow", "/"))
        self.btn_equal.setText(_translate("MainWindow", "="))
        self.btn0.setText(_translate("MainWindow", "0"))

    def add_functions(self):
        self.btn0.clicked.connect(lambda: self.write_number(self.btn0.text()))
        self.btn1.clicked.connect(lambda: self.write_number(self.btn1.text()))
        self.btn2.clicked.connect(lambda: self.write_number(self.btn2.text()))
        self.btn3.clicked.connect(lambda: self.write_number(self.btn3.text()))
        self.btn4.clicked.connect(lambda: self.write_number(self.btn4.text()))
        self.btn5.clicked.connect(lambda: self.write_number(self.btn5.text()))
        self.btn6.clicked.connect(lambda: self.write_number(self.btn6.text()))
        self.btn7.clicked.connect(lambda: self.write_number(self.btn7.text()))
        self.btn8.clicked.connect(lambda: self.write_number(self.btn8.text()))
        self.btn9.clicked.connect(lambda: self.write_number(self.btn9.text()))
        self.btn_plus.clicked.connect(lambda: self.write_number(self.btn_plus.text()))
        self.btn_minus.clicked.connect(lambda: self.write_number(self.btn_minus.text()))
        self.buton_mult.clicked.connect(lambda: self.write_number(self.buton_mult.text()))
        self.button_division.clicked.connect(lambda: self.write_number(self.button_division.text()))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
